spring.application.name=demo

# ===============================
# POSTGRESQL CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/blazeshort
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update

# ===============================
# REDIS CONFIG
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000